package ru.jobhunter.infrastructure.llm.routing;

import org.junit.jupiter.api.Test;
import ru.jobhunter.core.application.port.out.llm.LlmGenerationOptions;
import ru.jobhunter.core.application.port.out.llm.LlmGenerationRequest;
import ru.jobhunter.core.application.port.out.llm.LlmGenerationResponse;
import ru.jobhunter.core.application.port.out.llm.LlmMessage;
import ru.jobhunter.core.application.port.out.llm.LlmUsage;

import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;

class LlmRoutingPortTest {

    @Test
    void shouldUseOpenRouterWhenOllamaIsUnavailable() {
        LlmGenerationRequest request = request();

        LlmGenerationResponse fallbackResponse =
                new LlmGenerationResponse(
                        "openrouter",
                        "openrouter/free",
                        "Generated by OpenRouter fallback",
                        LlmUsage.unknown()
                );

        RecordingLlmProvider ollama = new RecordingLlmProvider(
                "ollama",
                CompletableFuture.failedFuture(
                        new LlmProviderUnavailableException(
                                "ollama",
                                LlmFailureCategory.NETWORK_UNAVAILABLE,
                                "Ollama connection refused"
                        )
                )
        );

        RecordingLlmProvider openRouter = new RecordingLlmProvider(
                "openrouter",
                CompletableFuture.completedFuture(fallbackResponse)
        );

        LlmRoutingPort routingPort = new LlmRoutingPort(
                ollama,
                Optional.of(openRouter)
        );

        LlmGenerationResponse response = routingPort.generate(request).join();

        assertSame(fallbackResponse, response);
        assertEquals(1, ollama.generateCalls());
        assertEquals(1, openRouter.generateCalls());
        assertSame(request, ollama.lastRequest());
        assertSame(request, openRouter.lastRequest());
    }

    @Test
    void shouldNotCallFallbackForNonProviderFailure() {
        LlmGenerationRequest request = request();

        RecordingLlmProvider ollama = new RecordingLlmProvider(
                "ollama",
                CompletableFuture.failedFuture(
                        new IllegalStateException("Prompt contract is invalid")
                )
        );

        RecordingLlmProvider openRouter = new RecordingLlmProvider(
                "openrouter",
                CompletableFuture.completedFuture(
                        new LlmGenerationResponse(
                                "openrouter",
                                "openrouter/free",
                                "Must not be used",
                                LlmUsage.unknown()
                        )
                )
        );

        LlmRoutingPort routingPort = new LlmRoutingPort(
                ollama,
                Optional.of(openRouter)
        );

        CompletionException exception = assertThrows(
                CompletionException.class,
                () -> routingPort.generate(request).join()
        );

        assertEquals(
                "Prompt contract is invalid",
                exception.getCause().getMessage()
        );
        assertEquals(1, ollama.generateCalls());
        assertEquals(0, openRouter.generateCalls());
    }

    @Test
    void shouldUseOpenRouterWhenOllamaIsExcludedForRetry() {
        LlmGenerationResponse fallbackResponse =
                new LlmGenerationResponse(
                        "openrouter",
                        "openrouter/free",
                        "Generated by OpenRouter",
                        LlmUsage.unknown()
                );

        RecordingLlmProvider ollama = new RecordingLlmProvider(
                "ollama",
                CompletableFuture.completedFuture(
                        new LlmGenerationResponse(
                                "ollama",
                                "qwen3:4b",
                                "This provider must not be called",
                                LlmUsage.unknown()
                        )
                )
        );

        RecordingLlmProvider openRouter = new RecordingLlmProvider(
                "openrouter",
                CompletableFuture.completedFuture(fallbackResponse)
        );

        LlmRoutingPort routingPort = new LlmRoutingPort(
                ollama,
                Optional.of(openRouter)
        );

        LlmGenerationResponse response = routingPort.generate(
                request().excludingProvider("ollama")
        ).join();

        assertSame(fallbackResponse, response);
        assertEquals(0, ollama.generateCalls());
        assertEquals(1, openRouter.generateCalls());
    }

    private LlmGenerationRequest request() {
        return new LlmGenerationRequest(
                "generate-cover-letter",
                List.of(
                        LlmMessage.system("You are a career assistant."),
                        LlmMessage.user("Generate a concise cover letter.")
                ),
                LlmGenerationOptions.coverLetter()
        );
    }

    private static final class RecordingLlmProvider implements LlmProvider {

        private final String providerId;
        private final CompletableFuture<LlmGenerationResponse> response;

        private int generateCalls;
        private LlmGenerationRequest lastRequest;

        private RecordingLlmProvider(
                String providerId,
                CompletableFuture<LlmGenerationResponse> response
        ) {
            this.providerId = providerId;
            this.response = response;
        }

        @Override
        public String providerId() {
            return providerId;
        }

        @Override
        public CompletableFuture<LlmGenerationResponse> generate(
                LlmGenerationRequest request
        ) {
            generateCalls++;
            lastRequest = request;

            return response;
        }

        private int generateCalls() {
            return generateCalls;
        }

        private LlmGenerationRequest lastRequest() {
            return lastRequest;
        }
    }

}